dist: trusty # needed for headles chrome
language: node_js
cache:
  npm: true
  directories:
    - $HOME/.npm
    - $HOME/build/$TRAVIS_REPO_SLUG/components/node_modules/

node_js:
  - 12
  - 11
  - 10

env:
  - NODE_ENV=develop

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 10

branches:
  only:
    - master
    - next
    - develop
  except:
    - /^v[0-9]+\.[0-9]+$/

# explicit use of default tasks
install: npm ci
script: npm test

stages:
  - test
  - release

jobs:
  allow_failures:
    - node_js: 10
  include:
    - stage: release
      if: branch = next AND type IN (push) AND tag IS blank
      node_js: 12
      script: skip
      install: skip
      before_deploy:
        - npm i -g semantic-release
        - npm i -g @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/git @semantic-release/github semantic-release-slack-bot
      deploy:
        tags: false
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: next
          tags: false
