dist: trusty # needed for headles chrome
language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/build/$TRAVIS_REPO_SLUG/components/node_modules/

node_js:
  - 12
  - 11
  - 10

matrix:
  fast_finish: true
  allow_failure:
    - node_js: 10

env:
  - NODE_ENV: develop

branches:
  only:
    - master
    - next
    - develop

install: yarn install
script: yarn lint && yarn karma && NODE_ENV=production yarn build

stages:
  - test
  - release

jobs:
  fast_finish: true
  allow_failure:
    - node_js: 10
  include:
    - stage: build
      script: npm run build
      name: 'Node.js: 12'
      node_js: 12
    - script: npm run build
      name: 'Node.js: 11'
      node_js: 11
    - script: npm run build
      name: 'Node.js: 10'
      node_js: 10
      allow_failure: true
    - stage: release
      if: branch = next AND type IN (push)
      node_js: 12
      script: skip
      install: skip
      before_deploy:
        - npm i -g semantic-release
        - npm i -g @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/git @semantic-release/github semantic-release-slack-bot
      deploy:
        tags: false
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch:
            - next
            - /^!\d\.\d\.\d/
          tags: false
